name: Dev snapshot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version string
        id: version
        run: |
          VERSION=""
          if git describe --tags --exact-match >/dev/null 2>&1; then
            VERSION=$(git describe --tags --exact-match)
          elif git describe --tags --abbrev=0 >/dev/null 2>&1; then
            VERSION=$(git describe --tags --abbrev=0)-dev
          else
            VERSION=dev
          fi
          HASH=$(git rev-parse --short=6 HEAD)
          DATETIME=$(date -u +'%Y%m%d-%H%M')
          VERSION_STRING="${VERSION}-${HASH}-${DATETIME}"
          echo "VERSION_STRING=$VERSION_STRING" >> $GITHUB_ENV

      - name: Show version string
        run: |
          echo "Build version: ${{ env.VERSION_STRING }}"

      - name: Set up Lua 5.1
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1.5"

      - name: Set up LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies
        run: luarocks install --tree=lua_modules --deps-only mudlet-package-dev-1.rockspec

      - name: Install busted
        run: luarocks install --tree=lua_modules busted

      - name: Run tests
        run: chmod +x ./scripts/run_tests.sh && ./scripts/run_tests.sh

      - name: Compose build context
        run: chmod +x ./scripts/compose_build_context.sh && ./scripts/compose_build_context.sh

      - name: Add version manifest to build context
        run: |
          mkdir -p muddler/src/resources
          echo "${{ env.VERSION_STRING }}" > muddler/src/resources/version.txt

      - name: Inject version into build context
        run: chmod +x ./scripts/inject_version.sh && ./scripts/inject_version.sh "${{ env.VERSION_STRING }}"

      - name: Build with muddler
        uses: demonnic/build-with-muddler@v1.4
        with:
          workingDir: muddler

      - name: Upload dev snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: muddler_luarocks_starter-${{ env.VERSION_STRING }}.mpackage
          path: muddler/build/muddler_luarocks_starter.mpackage
          retention-days: 14
